r={};
r={r{:},struct('name','L2b12','seq','GGG CUUUUCCGUAUAUCUCGCCAG GCUGUC ACCGGAUGUGCUUUCCGGUCUGAUGAGUCCGUUGUCCAUACCAGCAUCGUCUUGAUGCCCUUGGCAGGGACGGGACGGAGGACGAAACAGC GUGGUCCAAGUGAUUCCCAAA')};
r={r{:},struct('name','BT384-Directs2-193267','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAgggagaTCCGGTCTGATGAGTCCATACCAGCATCGTCTTGATGCCCTTGGCAGGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT385-Directs1-202251','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAATACCAGCATCGTCTTGATGCCCTTGGCAGTCCGGTCTGATGAGTCCctgtaaGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT386-Directs1-202267','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAATACCAGCATCGTCTTGATGCCCTTGGCAGTCCGGTCTGATGAGTCCctgcaaGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT387-TxLib-22673','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGgATACCAGCATCGTCTTGATGCCCTTGGCAGcgatgAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT388-L2b12-153121','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGTTGTCCATACCAGCaaaGTCTTgctGCCCTTGGCAGGGACGGGACGGAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT389-Directs1-202625','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAATACCAGCATCGTCTTGATGCCCTTGGCAGTCCGGTCTGATGAGTCCcctatcGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT390-L2b12-152326','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGTTGTCCATACCAGCgccGTCTTggaGCCCTTGGAAGGGACGGGACGGAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT391-L2b12-131582','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGTTGTCCataCCAGCATCGTCTTGATGCCCTTGGcttGGACGGGACGGAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
ntrials=20;
i=1;
while i<=ntrials
  fprintf('Running trial %d\n', i);
  for k=1:length(r)
    fprintf('Running %s\n', r{k}.name);
    r{k}=ribofold(r{k}.name,r{k}.seq,'ntrials',i);
    if length(r{k}.trial)>i
      i=min(ntrials,length(r{k}.trial));
    end
  end
  i=i+1;
end
tmin=500;
fprintf('Name                  Ribo  Apta Cnt\n');
for i=1:length(r)
  s=r{i}.summaryhelix;
  sel=s.time>=tmin;
  fprintf('%-20.20s %5.3f %5.3f %d\n',r{i}.name,mean(s.fracribo(sel)),mean(s.fracapt(sel)),length(r{i}.trial));
end
