r={};
r={r{:},struct('name','L2b12','seq','GGG CUUUUCCGUAUAUCUCGCCAG GCUGUC ACCGGAUGUGCUUUCCGGUCUGAUGAGUCCGUUGUCCAUACCAGCAUCGUCUUGAUGCCCUUGGCAGGGACGGGACGGAGGACGAAACAGC GUGGUCCAAGUGAUUCCCAAA')};
r={r{:},struct('name','BT384','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAgggagaTCCGGTCTGATGAGTCCATACCAGCATCGTCTTGATGCCCTTGGCAGGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT385','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAATACCAGCATCGTCTTGATGCCCTTGGCAGTCCGGTCTGATGAGTCCctgtaaGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT386','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAATACCAGCATCGTCTTGATGCCCTTGGCAGTCCGGTCTGATGAGTCCctgcaaGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT387','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGgATACCAGCATCGTCTTGATGCCCTTGGCAGcgatgAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT388','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGTTGTCCATACCAGCaaaGTCTTgctGCCCTTGGCAGGGACGGGACGGAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT389','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGAATACCAGCATCGTCTTGATGCCCTTGGCAGTCCGGTCTGATGAGTCCcctatcGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT390','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGTTGTCCATACCAGCgccGTCTTggaGCCCTTGGAAGGGACGGGACGGAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
r={r{:},struct('name','BT391','seq','GGG CTTTTCCGTATATCTCGCCAG GCTGTC ACCGGATGTGCTTTCCGGTCTGATGAGTCCGTTGTCCataCCAGCATCGTCTTGATGCCCTTGGcttGGACGGGACGGAGGACGAAACAGC GTGGTCCAAGTGATTCCCAAA')};
for i=1:15
  fprintf('Running trial %d\n', i);
  for k=1:length(r)
    fprintf('Running %s\n', r{k}.name);
    r{k}=ribofold(r{k}.name,r{k}.seq,'ntrials',i);
  end
end
tmin=500;
fprintf('Name       Ribo Apta\n');
for i=1:length(r)
  sel=r{i}.summary.time>=tmin;
  fprintf('%-10.10s %5.3f %5.3f\n',r{i}.name,mean(r{i}.summary.fracribo(sel)),mean(r{i}.summary.fracapt(sel)));
end